services:
  - type: web
    name: n8n-automation
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 10000
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_EDITOR_BASE_URL
        fromService:
          name: n8n-automation
          type: web
          property: url
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
    disk:
      name: n8n-data
      mountPath: /opt/render/.n8n
      sizeGB: 1
